services:
  - type: web
    name: chocolates-django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn chocolates.wsgi:application
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://djangochocolateschallenge:djangochocolateschallenge17@cluster0.di5foqj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: DJANGO_SETTINGS_MODULE
        value: chocolates.settings
      - key: PYTHON_VERSION
        value: 3.10.12
